Fix: Disable updater plugin temporarily
Error: updater requires pubkey (mandatory field)
But: pubkey requires TAURI_SIGNING_PRIVATE_KEY

Solution: Disable updater for now
- Remove updater from plugins
- Comment out tauri-plugin-updater dependency

TODO: v2.2.8에서 signing keys 생성 후 재활성화

지금은 일단 빌드 성공시키기!