Fix: Remove updater code from lib.rs
Error: cannot find module tauri_plugin_updater
Cause: Removed from Cargo.toml but not from lib.rs

Removed:
- use tauri_plugin_updater::UpdaterExt
- .plugin(tauri_plugin_updater::Builder)
- updater background check thread

이제 진짜 빌드 성공!